### ISSUE TITLE
Not compatible to 1.10

### ISSUE THREAD

**Issue by XLPmc** [DarkBlade12/ParticleEffect#17]
This library doesn't support the minecraft version 1.10
It looks like it's something with the class name it is now called "PacketPlayOutWorldParticles" instead of "Packet63WorldParticles".
https://github.com/linouxis9/mc-dev-1.10.2/blob/a8d53df8e83c79e29ab988909c2fbfc3d4f9af1a/net/minecraft/server/PacketPlayOutWorldParticles.java

I'd like it if you fix the problem, thanks.

Example

Code:  `ParticleEffect.SNOW_SHOVEL.display(0,0,0,1,1000,player.getLocation(), recivers);`
---- Exeption ----

_[12:00:37 ERROR]: Could not pass event PlayerInteractEvent to XLP-CORE vBETA3.0.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:946) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
**Caused by: me.xlp.core.importeduitils.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library**
        at me.xlp.core.importeduitils.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1418) ~[?:?]
        at me.xlp.core.importeduitils.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1349) ~[?:?]
        at me.xlp.core.importeduitils.ParticleEffect.display(ParticleEffect.java:604) ~[?:?]
        at me.xlp.game.lobby.LobbyEvents.boost(LobbyEvents.java:173) ~[?:?]
        at me.xlp.core.managers.HotBar.execute(HotBar.java:110) ~[?:?]
        at me.xlp.core.managers.HotBar.onUse(HotBar.java:79) ~[?:?]
        at me.xlp.core.managers.HotBar.onUse(HotBar.java:72) ~[?:?]
        at me.xlp.core.main.Events.onPlayerUse(Events.java:191) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        ... 18 more
Caused by: java.lang.**ClassNotFoundException: net.minecraft.server.v1_10_R1.Packet63WorldParticles**
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
        at java.lang.Class.forName(Class.java:260) ~[?:1.8.0_25]
        at me.xlp.core.importeduitils.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:414) ~[?:?]
        at me.xlp.core.importeduitils.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1412) ~[?:?]
        at me.xlp.core.importeduitils.ParticleEffect$ParticlePacket.<init>(ParticleEffect.java:1349) ~[?:?]
        at me.xlp.core.importeduitils.ParticleEffect.display(ParticleEffect.java:604) ~[?:?]
        at me.xlp.game.lobby.LobbyEvents.boost(LobbyEvents.java:173) ~[?:?]
        at me.xlp.core.managers.HotBar.execute(HotBar.java:110) ~[?:?]
        at me.xlp.core.managers.HotBar.onUse(HotBar.java:79) ~[?:?]
        at me.xlp.core.managers.HotBar.onUse(HotBar.java:72) ~[?:?]
        at me.xlp.core.main.Events.onPlayerUse(Events.java:191) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-a9631d2-67b2424]
        ... 18 more_

Thanks ;)

**Comment by XLPmc** [comment]
FIXED
[FIX](https://github.com/DarkBlade12/ParticleEffect/pull/12/commits/cc8d96b112db49b8e12b7b95da1880cac4a638fd)
